name: Build and Release

on:
  push:
    branches: [master]
    tags:
      - "v*" # Run workflow on version tags, e.g. v1.0.0
  pull_request:
    branches: [master]

# Add permissions needed for creating releases
permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for git describe to work properly

      - name: Setup Linux build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make

      - name: Build for Linux
        run: |
          make COMP=gcc HOST=Linux bits=64 static=yes
          mv bbpPairings.exe bbpPairings-linux

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bbpPairings-linux
          path: bbpPairings-linux
          retention-days: 7

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Set up release date
        if: github.event_name == 'schedule'
        id: date
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create tag for scheduled run
        if: github.event_name == 'schedule'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        if: github.event_name == 'schedule'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create and push tag for daily build
        if: github.event_name == 'schedule'
        run: |
          TAG_NAME="nightly-${{ steps.date.outputs.RELEASE_DATE }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bbpPairings-linux/bbpPairings-linux
          tag_name: ${{ github.event_name == 'schedule' && format('nightly-{0}', steps.date.outputs.RELEASE_DATE) || github.ref_name }}
          name: ${{ github.event_name == 'schedule' && format('Daily build {0}', steps.date.outputs.RELEASE_DATE) || github.ref_name }}
          draft: false
          prerelease: ${{ github.event_name == 'schedule' }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
